STOP_PHRASES = {

    "that",
    "this",
    "which",
    "they",
    "them",
    "what",
    "some",
    "each",
    "time",
    "year",
    "people",
    "link",
    "( link",
    "a new window",
    "share image share",
    "the original",
    "twitter facebook",
    "the company",
    "the world",
    "the us",
    "the united states",
    "the new york times",
    "associated press",
    "reuters",
    "cnbc",
    "deloitte insights",
    "epoch ai",
    "cs1 maint",
    "issn",
    "archival service"
}